version: "3"
services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: nginx/production/Dockerfile
  #   ports: 
  #     - "8080:80"
  #   depends_on:
  #     - php
  #   networks:
  #     - internal
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    ports:
      - "8080:80"
#     networks:
#       - internal
# networks:
#   internal:
#     driver: bridge