apiVersion: v1
kind: Pod
metadata:
  name: clickhouse-backup
  namespace: env-rwj4sm
spec:
  containers:
  - image: yandex/clickhouse-server:19.14
    imagePullPolicy: IfNotPresent
    command: ['sleep', '10000']
    name: clickhouse-rwj4sm
    ports:
    - containerPort: 8123
      name: http-port
      protocol: TCP
    - containerPort: 9000
      name: tcp-port
      protocol: TCP
    - containerPort: 9009
      name: inter-http-port
      protocol: TCP
    securityContext:
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: clickhouse-backup
  nodeName: ip-192-168-52-197.eu-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: clickhouse-rwj4sm-headless
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300