apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-backup-cron
spec:
  # every day at 00:00
  schedule: "5 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      backoffLimit: 100
      completions: 1
      parallelism: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: run-backup-cron
              image: yandex/clickhouse-server:19.14
              imagePullPolicy: IfNotPresent
              env:
                # use first replica in each shard, use `kubectl get svc | grep test-backups`
                - name: CLICKHOUSE_HOST
                  value: clickhouse-rwj4sm
                - name: CLICKHOUSE_PORT
                  value: "9000"
                - name: BACKUP_USER
                  value: default
                - name: BACKUP_PASSWORD
                  value: ""
                - name: REMOTE_STORAGE 
                  value: 's3'
                - name: BACKUPS_TO_KEEP_REMOTE 
                  value: '1'
                - name: S3_ACCESS_KEY 
                  value: 'AKIA2H6TKJHILI6YZPGO'
                - name: S3_SECRET_KEY 
                  value: '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'
                - name: S3_BUCKET
                  value: 'bnsclickhousebucket'
                - name: S3_ENDPOINT 
                  value: 'http://bnsclickhousebucket.s3.eu-west-1.amazonaws.com/'
                - name: S3_REGION 
                  value: 'eu-west-1'
                - name: S3_ACL 
                  value: 'private'
                - name: S3_FORCE_PATH_STYLE 
                  value: 'true'
                - name: S3_PATH 
                  value: 'backup'
                - name: S3_DISABLE_SSL 
                  value: 'true'
                - name: S3_DEBUG 
                  value: 'false'
              command:
                - bash
                - -cx
                - BACKUP_NAME="my_backup_$(date -u +%Y-%m-%dT%H-%M-%S)"; /usr/bin/wget https://github.com/AlexAkulov/clickhouse-backup/releases/download/v0.6.3/clickhouse-backup.tar.gz --no-check-certificate; /bin/tar -xf clickhouse-backup.tar.gz ; cd clickhouse-backup/ ; mkdir -p /var/lib/clickhouse/shadow; ./clickhouse-backup tables; ./clickhouse-backup create $BACKUP_NAME; ./clickhouse-backup upload $BACKUP_NAME;
