apiVersion: v1
kind: Pod
metadata:
  labels:
    run: debugtools
  name: debugtools
  namespace: env-zhng4w
spec:
  containers:
  - image: praqma/network-multitool
    imagePullPolicy: Always
    name: debugtools
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wnk8c
      readOnly: true
    - name: tz-config
      mountPath: /etc/localtime
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-192-168-36-186.eu-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-wnk8c
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - name: tz-config
    hostPath:
      path: /usr/share/zoneinfo/Europe/London
      type: File